version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: nestjs_app
      MYSQL_USER: nestjs_user
      MYSQL_PASSWORD: nestjs_password
    ports:
      - "3306:3306"
